### ISSUE TITLE
Visual Studio 2019 support missing in BISM Normalizer

### ISSUE THREAD

**Issue by fmms** [microsoft/Analysis-Services#30] opened 2019-04-23 12:56 UTC
Hi,

i have moved to VS2019. 

Analysis Services are supported (see https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjects). However, BISM Normalizer (see https://marketplace.visualstudio.com/items?itemName=ChristianWade.BISMNormalizer3 ) is not available yet.
Do you have any timeline? Without BISM normlizer a important piece is missing for me.

regards

**Comment by shswindell42** [comment] 2019-05-30 20:18
I've created a pull request #31 to address this. I was able to install it into my instance of VS 2019 and it seems to be working without issue. Perhaps this will get pushed up to the marketplace.

**Comment by Guavaq** [comment] 2019-06-27 01:04
Hi @shswindell42 how did you go about getting the pull request and get it working in VS 2019?

I am not sure how to do this, any advice would be appreciated.

**Comment by shswindell42** [comment] 2019-06-27 13:29
You should be able to pull my fork of this [https://github.com/shswindell42/Analysis-Services/tree/BISMNormalizerVS2019](url), open the BismNormalizer.sln solution file and build it. That should create a .vsix file that you can run to install the extension into VS 2019. The file will be created in the BismNormalizer\bin\Release folder. 

After it's installed the Tabular Comparison Tool will be available under the Tools menu.

**Comment by Guavaq** [comment] 2019-06-28 01:27
Thanks for the details. 

I am no developer and for some reason it was complaining about the Bismnormalizer.TabularCompare namespace that it could not find.

Any idea's on what to do, or if I could get a copy of the VSIX?

**Comment by christianwade** [comment] 2019-12-14 04:28
Thanks all for the responses and sorry for the delayed response. I plan to monitor this more closely in future! You're probably aware BISM Normalizer works with VS 2019 now

**Comment by ashishegon** [comment] 2020-07-27 12:56
> 
> 
> Thanks all for the responses and sorry for the delayed response. I plan to monitor this more closely in future! You're probably aware BISM Normalizer works with VS 2019 now

The BISM Normalizer is not working on VS 2019 version 16.6.5 with latest Analysis Services extension. Kindly help, its urgent.

**Comment by christianwade** [comment] 2020-07-28 23:14
What's the problem you are experiencing? Is it the following error?
Method not found: 'Microsoft.AnalysisServices.Tabular.Model Microsoft.AnalysisServices.Database.get_Model()'.

I have been unable to repro this. Apparently it may be caused by an SSDT bug with SSIS. If you want to send me the project files (assuming it repros locally without a connection to the server), I'm happy to try

**Comment by JuanesPedro** [comment] 2020-07-30 14:45
> What's the problem you are experiencing? Is it the following error?
> Method not found: 'Microsoft.AnalysisServices.Tabular.Model Microsoft.AnalysisServices.Database.get_Model()'.
> 
> I have been unable to repro this. Apparently it may be caused by an SSDT bug with SSIS as some users reported that uninstalling the SSIS extension resolved it. Please let me know if you experience the same. If you want to send me the project files (assuming it repros locally without a connection to the server), I'm happy to try

Hi Christian,

I'm getting this error.
- configured a new laptop,  installed VS2019 / SSIS / SSAS extensions en BISM.
- imported Tabular project from Analysis Server 2016 
- did some changes
- As soon as I hit the OK button after comparing the project with the database I get this error.

BISM Normalizer 5.4.4.2
Analysis Services Projects 2.9.12
Integration Services Projects 3.8
Studio 16.6.5

Disabling the Integration Services Projects resolves the problem like you said.

On my old laptop everything worked just fine, so a looked a bit deeper into the differences
As it turned out:
Integration Services Projects was version 3.7
Analysis Services Projects version 2.9.10

I upgraded Integration Services Projects to 3.8 and the same problem appeared.

**Comment by ashishegon** [comment] 2020-07-30 15:00
it looks like SSIS/Integration update which caused the issue. Since i upgraded the VS, Analysis Services and Integration updates in the Visual Studio. To workaround, installed the VS 16.2, with no further updates, since the work was getting impacted. Hope this helps others and the issue is resolved for others. Thanks.

**Comment by vmihay** [comment] 2021-03-16 08:19
For those searching for solution, I found two workarounds that work. I tried the first and it worked.

================================================================================

> I had the same issue. Instead of uninstalling, i just disabled SSIS extension and it worked. Now whenever i have to use SSIS , i just need to re-enable SSIS before using. Its annoying but works quite well.

_Originally posted by @pankajpandya in https://github.com/microsoft/Analysis-Services/issues/67#issuecomment-768916518_

================================================================================

> Its a known problem with the SSIS 3.12 install.
> Suggest you download SSIS 3.11.1

https://marketplace.visualstudio.com/items?itemName=SSIS.SqlServerIntegrationServicesProjects

_Originally posted by @MickealpDavis in https://github.com/microsoft/Analysis-Services/issues/67#issuecomment-772933182_

**Comment by AndrewBorst** [comment] 2021-05-18 18:05
Upgrading to SSIS 3.13 didn't fix the bug but disabling the extension, closing the Visual Studio, and re-opening is still a decent workaround.

**Closed** 2024-08-17 21:46 UTC
